### ISSUE TITLE
Export transform function

### ISSUE THREAD

**Issue by cojack** [caio-ribeiro-pereira/field-normalizer#1]
Hi, 
I would love to have `transform` function exported as well

**Comment by caio-ribeiro-pereira** [comment]
The transform fucntion exposed could cause bugs, because it's not related to the main functions of this lib, and I will soon change this lib to not depend on change-case module

**Comment by cojack** [comment]
Okey, what I had in mind, was to pass the name of the method to transform by argument, so that's why I created this issue.

**Comment by caio-ribeiro-pereira** [comment]
@cojack you can do this dynamic method call without using transform, example:

``` javascript
const FNZ = require('field-normalizer');
const actions = ['toSnakeCase', 'toConstantCase'];
const obj = { fullName: 'Test' };
const result = actions.map(action => FNZ[action](obj));
console.log(result); // [{ full_name: 'Test' }, { FULL_NAME: 'Test' }];
```

**Comment by cojack** [comment]
I know, but this looks bad, I'd like to have a factory for that.

**Comment by caio-ribeiro-pereira** [comment]
@cojack okay, a public factory method will looks good, please wait for 0.0.5, I will export transform() in a safe function.

**Comment by caio-ribeiro-pereira** [comment]
@cojack as promised, the v0.0.5 is live, with transform() public for use, I hope you enjoy and please help us sharing or giving star in this repo! have a nice weekend!
