### ISSUE TITLE
Add kabob-case

### ISSUE THREAD

**Issue by tracker1** [caio-ribeiro-pereira/field-normalizer#2]
Would suggest adding kabob-case (hyphen separated).

**Comment by caio-ribeiro-pereira** [comment]
@tracker1 the kabob case is not a good pattern for javascript, but this case can be useful when you transform and send the object to a backend.

Next version I will add this kabob case and dotcase too, thanks for the suggestion!

**Comment by caio-ribeiro-pereira** [comment]
@tracker1 as promised, the v0.0.4 is live and I added `toParamCase() => { full-name, contact-email }` and `toHeaderCase() => { Full-Name, Contact-Email }`

https://github.com/caio-ribeiro-pereira/field-normalizer/commit/9534c3d6cd12524f9638e05f8b62f30dd23541ca

Thank you for the feedbacks! This issue will be closed!

**Comment by tracker1** [comment]
@caio-ribeiro-pereira thanks... was mostly for completeness sake since it's a common pattern.  I use it for file naming, so there are times where that's the underlying reference, but it's more an exception than a rule.
