### ISSUE TITLE
Doesn't handle arrays

### ISSUE THREAD

**Issue by kleber-gueriero** [caio-ribeiro-pereira/field-normalizer#4]
When an object A has an attribute B as an array, it doesn't normalize the items inside this array.
e.g: 
```
a = { b: [ { c_minus: 1} ] }
FieldNormalizer.toCamelCase(a)
=> { b: [ { c_minus: 1} ] }
```

**Comment by caio-ribeiro-pereira** [comment]
Thanks for sending this PR (https://github.com/caio-ribeiro-pereira/field-normalizer/pull/5)
I will update soon, this bugfix!
