### ISSUE TITLE
Unhandled objects can bug whole code flow

### ISSUE THREAD

**Issue by kleber-gueriero** [caio-ribeiro-pereira/field-normalizer#6]
When using it to normalize something like an API request response, sometimes the incoming object won't attend to the "valid object"'s of the lib.
In this case, just returning the original object would make everything work just as expected, while the current behaviour breaks the application.

e.g.:
If I call `FieldNormalizer.toCamelCase(error.errors)`, where `error` has a format like this:
```
{
  "errors": {
    "user_id": ["cant be blank", "already in use"],
    "amount": ["cant be blank"]
  }
}
```

**Comment by caio-ribeiro-pereira** [comment]
Your PR is now live on npm v0.0.8, thanks dude!
https://www.npmjs.com/package/field-normalizer/v/0.0.8
